export const LOAD_AUTOCOMPLETE_INITIATED = "LOAD_AUTOCOMPLETE_INITIATED";
export const LOAD_AUTOCOMPLETE_SUCCESS = "LOAD_AUTOCOMPLETE_SUCCESS";
export const LOAD_AUTOCOMPLETE_ERROR = "LOAD_AUTOCOMPLETE_ERROR";

export const LOAD_RANDOM_INITIATED = "LOAD_RANDOM_INITIATED";
export const LOAD_RANDOM_SUCCESS = "LOAD_RANDOM_SUCCESS";
export const LOAD_RANDOM_ERROR = "LOAD_RANDOM_ERROR";
